{
  "type": "relationship",
  "id": "relationship--a5b41632-a553-4abe-aa68-9ce6898e642d",
  "created": "2021-10-13T22:50:48.9Z",
  "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
  "description": "(Citation: Symantec WastedLocker June 2020)",
  "external_references": [
    {
      "description": "Symantec Threat Intelligence. (2020, June 25). WastedLocker: Symantec Identifies Wave of Attacks Against U.S. Organizations. Retrieved May 20, 2021.",
      "source_name": "Symantec WastedLocker June 2020",
      "url": "https://symantec-enterprise-blogs.security.com/blogs/threat-intelligence/wastedlocker-ransomware-us"
    }
  ],
  "modified": "2021-10-13T22:50:48.9Z",
  "object_marking_refs": [
    "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
  ],
  "relationship_type": "uses",
  "source_ref": "intrusion-set--01e28736-2ffc-455b-9880-ed4d1407ae07",
  "spec_version": "",
  "target_ref": "tool--ff6caf67-ea1f-4895-b80e-4bb0fc31c6db",
  "x_mitre_attack_spec_version": "",
  "x_mitre_modified_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
  "x_mitre_version": "1.0"
}
